# fly.toml app configuration file generated for myapp-api-rust on 2025-07-31T21:06:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'myapp-api-rust'
primary_region = 'sin'

[build]

[env]
  PORT = '5001'
  HOST = '0.0.0.0'

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
